"""Audit trail router"""
from __future__ import annotations

import asyncio
from typing import Optional
from uuid import UUID

from fastapi import APIRouter, Depends, Query

from auth.supabase_auth import UserContext, verify_token
from database.supabase_client import get_supabase
from fastapi.responses import HTMLResponse, Response
import datetime

router = APIRouter()


@router.get("")
async def get_audit_logs(
    entity_type: Optional[str] = None,
    entity_id: Optional[str] = None,
    limit: int = Query(50, le=200),
    skip: int = 0,
    user: UserContext = Depends(verify_token),
):
    """
    Retrieve audit logs. Admins see all; others see their department only.
    """
    sb = get_supabase()
    q = (
        sb.table("audit_logs")
        .select("*")
        .order("created_at", desc=True)
        .range(skip, skip + limit - 1)
    )

    if entity_type:
        q = q.eq("entity_type", entity_type)
    if entity_id:
        q = q.eq("entity_id", entity_id)

    # Non-admin: filter to own user_id only
    if user.role not in ("admin", "senior_officer"):
        q = q.eq("user_id", user.user_id)

    res = await asyncio.get_event_loop().run_in_executor(None, lambda: q.execute())
    return {"logs": res.data or [], "total": len(res.data or [])}

@router.get("/export")
async def export_audit_logs(
    entity_id: str,
    user: UserContext = Depends(verify_token),
):
    """
    Generate an RTI-proof PDF or HTML audit report for a specific evaluation/bidder.
    """
    sb = get_supabase()
    res = await asyncio.get_event_loop().run_in_executor(
        None, lambda: sb.table("audit_logs")
        .select("*")
        .eq("entity_id", entity_id)
        .order("created_at", desc=False)
        .execute()
    )
    logs = res.data or []
    
    html_content = f"""
    <html>
    <head>
        <title>RTI-Proof Audit Trail</title>
        <style>
            body {{ font-family: sans-serif; margin: 40px; }}
            h1 {{ color: #2c3e50; }}
            .header {{ border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 30px; }}
            .log-entry {{ border-left: 4px solid #3498db; padding-left: 15px; margin-bottom: 20px; }}
            .meta {{ color: #7f8c8d; font-size: 0.9em; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>TenderSense AI: Immutable Audit Trail</h1>
            <p><strong>Entity ID:</strong> {entity_id}</p>
            <p><strong>Generated On:</strong> {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p><em>This report was generated by TenderSense AI and is legally admissible as an evaluation record under Karnataka Transparency in Public Procurement Act 1999.</em></p>
        </div>
    """
    
    for log in logs:
        action = log.get('action', '')
        user_email = log.get('user_email', 'System/AI Agent')
        ts = log.get('created_at', '')
        html_content += f"""
        <div class="log-entry">
            <h3>{action}</h3>
            <p class="meta">By: {user_email} | Time: {ts}</p>
            <p><strong>Details:</strong> {str(log.get('new_value', ''))}</p>
        </div>
        """
        
    html_content += "</body></html>"
    
    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html_content).write_pdf()
        return Response(content=pdf_bytes, media_type="application/pdf", headers={"Content-Disposition": f"attachment; filename=audit_{entity_id}.pdf"})
    except ImportError:
        # Fallback to HTML if WeasyPrint (GTK) is not installed natively
        return HTMLResponse(content=html_content)
